[phases.setup]
nixPkgs = ['openjdk17', 'maven']

[phases.build]
cmds = ['mvn clean compile package -DskipTests']

[start]
cmd = 'java -Dspring.profiles.active=production -Dserver.port=$PORT -jar target/app-0.0.1-SNAPSHOT.jar'
